FROM golang:1.21.7-alpine3.19 as builder
WORKDIR /app
COPY ./ ./
RUN go build -o api ./cmd/api

FROM alpine:3.19 AS prod
WORKDIR /app
COPY --from=builder /app/api /app/
COPY --from=builder /app/packsizes.json /app/
ENTRYPOINT ["/app/api"]
