FROM golang:1.21.7-alpine3.19 as builder
WORKDIR /app
COPY ./ ./
RUN go build -o ui ./cmd/ui

FROM alpine:3.19 AS prod
WORKDIR /app
COPY --from=builder /app/ui /app/
COPY --from=builder /app/internal/ui/static /app/static
ENTRYPOINT ["/app/ui"]
