FROM golang:1.21.7-alpine3.19 as builder
WORKDIR /app
COPY ./ ./
RUN go build -o ui ./cmd/ui
RUN go build -o api ./cmd/api

FROM alpine:3.19 AS prod
RUN apk update && apk add --no-cache supervisor curl bash
WORKDIR /app
COPY --from=builder /app/ui /app/
COPY --from=builder /app/api /app/
COPY --from=builder /app/packsizes.json /app/
COPY --from=builder /app/supervisord.conf /app/
COPY --from=builder /app/internal/ui/static /app/static
CMD ["/usr/bin/supervisord", "-c", "/app/supervisord.conf"]